# ESLint configuration file for TypeScript based on Airbnb's style guide
# See https://github.com/AdguardTeam/CodeGuidelines/blob/master/JavaScript/Javascript.md
root: true
extends:
  - eslint:recommended
  - "plugin:@typescript-eslint/recommended"
  - airbnb-base
  - airbnb-typescript/base
  - plugin:jsdoc/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  project: tsconfig.eslint.json
plugins:
  - import
  - "@typescript-eslint"
rules:
  max-len:
    - error
    - code: 120
      comments: 120
      tabWidth: 4
      ignoreUrls: false
      ignoreTrailingComments: false
      ignoreComments: false
  "@typescript-eslint/indent":
    - error
    - 4
    - SwitchCase: 1
  import/prefer-default-export: off
  no-restricted-syntax:
    - error
    - LabeledStatement
    - WithStatement
  no-continue: off
  jsdoc/require-param-type: off
  jsdoc/require-returns-type: off
  arrow-body-style: off
  no-await-in-loop: off
  import/no-extraneous-dependencies: off
