---
version: 2
plan:
  project-key: AJL
  key: VSCODEADBLOCKSYNTAXBUILD
  name: vscode adblock syntax - build release
variables:
  dockerNode: adguard/node-ssh:18.13--1

stages:
  - Build:
      manual: false
      final: false
      jobs:
        - Build

Build:
  key: BUILD
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.YARN_DIR}: "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e
            ls -al

            # Install dependencies
            # swc core optional dependencies are needed for tests
            # but `--ignore-optional` will not install them
            # so we run `yarn install ${bamboo.varsYarn}` without `--ignore-optional`.
            # We need to install dependencies separately for client and server separately
            # because we use '--ignore-scripts' which prevents postinstall script from running.
            yarn install --silent --ignore-engines --ignore-platform --ignore-scripts
            cd client
            yarn install --silent --ignore-engines --ignore-platform --ignore-scripts
            cd ../server
            yarn install --silent --ignore-engines --ignore-platform --ignore-scripts
            cd ..

            # Create production build
            yarn prod

            # Cleanup
            rm -rf node_modules
            rm -rf client/node_modules
            rm -rf server/node_modules
    - inject-variables:
        file: out/build.txt
        scope: RESULT
        namespace: inject
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
        configuration:
          selectedRepository: defaultRepository
          tagName: v${bamboo.inject.version}
  # Store the .vsix file as a build artifact
  artifacts:
    - name: vscode-adblock.vsix
      location: out
      pattern: vscode-adblock.vsix
      shared: true
      required: true
  requirements:
    - adg-docker: true

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: true

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo
labels: []
other:
  concurrent-build-plugin: system-default
