---
version: 2
plan:
  project-key: AJL
  key: VSCODEADBLOCKSYNTAXINCR
  name: vscode adblock syntax - increment
variables:
  dockerNode: adguard/node-ssh:22.14--0

stages:
  - Increment:
      manual: true
      final: false
      jobs:
        - Increment

Increment:
  key: INCR
  docker:
    image: '${bamboo.dockerNode}'
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -laht

            pnpm increment
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skipci: Automatic increment build number'
          selectedRepository: defaultRepository
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh"
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

branches:
  create: manually
  delete: never
  link-to-jira: true

labels: []
other:
  concurrent-build-plugin: system-default
