---
version: 2
plan:
  project-key: AJL
  key: VSCODEADBLOCKSYNTAXTEST
  name: vscode adblock syntax - tests
variables:
  dockerNode: adguard/node-ssh:22.14--0

stages:
  - Build:
      manual: false
      final: false
      jobs:
        - Build

Build:
  key: BUILD
  docker:
    image: '${bamboo.dockerNode}'
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -laht

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}

            # Install dependencies
            pnpm install

            # Check TypeScript types
            pnpm test:compile

            # Run markdownlint
            pnpm lint:md

            # Run ESLint
            pnpm lint:ts

            # Run Jest tests
            pnpm test
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh"
  requirements:
    - adg-docker: true

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: []
other:
  concurrent-build-plugin: system-default
